In [1]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder


In [2]:
colors = (['red','green','yellow','red','green'])

In [3]:
colors

['red', 'green', 'yellow', 'red', 'green']

In [4]:
lb = LabelEncoder()

In [5]:
integer_encoded = lb.fit_transform(colors)

In [6]:
integer_encoded

array([1, 0, 2, 1, 0], dtype=int64)

In [7]:
lb.inverse_transform([1,0,2,0])

array(['red', 'green', 'yellow', 'green'], dtype='<U6')

In [9]:
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)

In [10]:
integer_encoded

array([[1],
       [0],
       [2],
       [1],
       [0]], dtype=int64)

In [11]:
onc = OneHotEncoder(sparse= False)

In [14]:
onehot_encoder = onc.fit_transform(integer_encoded)

C:\Users\Saurabh Somkuwar\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [15]:
onehot_encoder

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [16]:
import pandas as pd

In [18]:
df = pd.read_csv("1000_Companies.csv")

In [19]:
df.head()

R&D_Spend  Administration  Marketing_Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [20]:
df1 = df.State

In [21]:
df1.head()

0      New York
1    California
2       Florida
3      New York
4       Florida
Name: State, dtype: object

In [24]:
df1.isna().sum()

0

In [25]:
integer_encoded = lb.fit_transform(df1)

In [26]:
integer_encoded

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0,
       2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0,
       1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2,
       0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2,
       1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0,
       1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0,
       2, 0, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0,
       2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0,
       2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1,
       2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 0, 1,

In [27]:
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)

In [28]:
integer_encoded

array([[2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0],
       [2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [0],
    

In [29]:
onc = OneHotEncoder(sparse= False)

In [30]:
onehot_encoder = onc.fit_transform(integer_encoded)

C:\Users\Saurabh Somkuwar\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [31]:
df2 = pd.DataFrame(onehot_encoder, columns= ['California','Florida','New York'])

In [32]:
df2.head()

California  Florida  New York
0         0.0      0.0       1.0
1         1.0      0.0       0.0
2         0.0      1.0       0.0
3         0.0      0.0       1.0
4         0.0      1.0       0.0

In [33]:
new_df = df.join(df2)